version: "3.9"
services:
  web:

    build: .
    command: python /projects/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/projects

    ports:
      - "8000:8000"

    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - "DJANGO_SECRET_KEY=django-insecure-!kxa6&51#e!0=hr700_inh(r312#!!17go2@#teer!!h)s#71d"
    depends_on:
      - db

  db:

    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: