# Generated by Django 4.1.3 on 2022-12-23 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_post_repost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_child',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='repost',
            field=models.ManyToManyField(blank=True, to='social.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_child',
            field=models.ManyToManyField(blank=True, to='social.comment'),
        ),
    ]
