# Generated by Django 4.1.3 on 2022-12-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_remove_comment_comment_child_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_child',
            field=models.ManyToManyField(blank=True, related_name='comment_childs', to='social.comment'),
        ),
    ]
