# Generated by Django 4.1.3 on 2022-12-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_comment_comment_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SPO', 'Sports'), ('TEC', 'Tech'), ('ART', 'Art'), ('FAS', 'Fashion')], max_length=40)),
                ('post', models.ManyToManyField(related_name='categories', to='social.post')),
            ],
        ),
    ]
