# Generated by Django 4.1.3 on 2022-12-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='posts', to='social.category'),
        ),
    ]
