# Generated by Django 4.1.3 on 2022-12-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_remove_category_post_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('SPO', 'Sports'), ('TEC', 'Tech'), ('ART', 'Art'), ('FAS', 'Fashion')], max_length=40, null=True),
        ),
    ]
