# Generated by Django 4.1.3 on 2022-12-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_remove_category_category_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
