# Generated by Django 4.1.3 on 2023-03-13 18:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_alter_post_user_dislikes_alter_post_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
